# fly.toml app configuration file generated for node-js-church-presentation-app-v1 on 2025-09-06T13:45:49Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'node-js-church-presentation-app-v1'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
